type Feature = {
  icon: string;
  text: string;
  color: string;
  opacity?: boolean;
  badges?: { text: string; class: string }[];
};

type Plan = {
  name: string;
  description: string;
  price: number;
  period: string;
  features: Feature[];
  buttonText: string;
  buttonUrl: string;
  badge: string | null;
  featured: boolean;
};

export const pricingTabs = [
  { id: 'monthly', label: 'Virtual Private Container' },
  { id: 'vpn', label: 'VPN' },
];

export const pricingPlans: Record<string, Plan[]> = {
  monthly: [
    {
      name: 'Free Plan',
      description: 'Get started with basic hosting',
      price: 0,
      period: 'month',
      features: [
        { icon: 'cpu', text: '1 vCPU @ 2.4 GHz (shared)', color: 'text-green-400' },
        { icon: 'memory-stick', text: '2 GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '5 GB NVMe Storage', color: 'text-green-400' },
        { icon: 'mail-plus', text: '1 Email Account', color: 'text-green-400' },
        { icon: 'check', text: '1 Domain Slot', color: 'text-green-400' },
        { icon: 'database', text: '1 Database', color: 'text-green-400' },
        { icon: 'gauge', text: '10GB Bandwidth', color: 'text-yellow-400' },
        { icon: 'help-circle', text: 'Community Support', color: 'text-blue-400' },
      ],
      buttonText: 'Get Started',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/free-plan',
      badge: null,
      featured: false,
    },
    {
      name: 'Basic Plan',
      description: 'Perfect for individuals & starter websites',
      price: 5,
      period: 'month',
      features: [
        { icon: 'cpu', text: '3 vCPU @ 2.4  GHz (shared)', color: 'text-green-400' },
        { icon: 'memory-stick', text: '5 GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '20 GB NVMe Storage', color: 'text-green-400' },
        { icon: 'mail-plus', text: 'Unlimited Email Accounts', color: 'text-green-400' },
        { icon: 'check', text: '3 Domain Slots', color: 'text-green-400' },
        { icon: 'database', text: 'Unlimited Databases', color: 'text-green-400' },
        { icon: 'infinity', text: 'Unlimited Bandwidth', color: 'text-green-400' },
        { icon: 'help-circle', text: 'Basic Support', color: 'text-green-400' },
        { icon: 'network', text: 'Optional Add-on: Dedicated IP: $5 AUD / month', color: 'text-blue-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/basic-plan',
      badge: null,
      featured: false,
    },
    {
      name: 'Pro Plan',
      description: 'Ideal for growing businesses',
      price: 8,
      period: 'month',
      features: [
        { icon: 'check', text: 'Everything in the Basic Plan, plus:', color: 'text-green-400' },
        { icon: 'cpu', text: '4 vCPU @ 2.4  GHz (shared)', color: 'text-green-400' },
        { icon: 'memory-stick', text: '8 GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '30 GB NVMe Storage', color: 'text-green-400' },
        { icon: 'check', text: '8 Domain Slots', color: 'text-green-400' },
        { icon: 'hand-helping', text: 'Priority Support', color: 'text-green-400' },
        { icon: 'laptop-minimal-check', text: 'Early Developer Features', color: 'text-green-400' },
        { icon: 'check', text: 'VPN Access', color: 'text-green-400' },
        { icon: 'network', text: 'Optional Add-on: Dedicated IP: $5 AUD / month', color: 'text-blue-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/pro-plan',
      badge: '⭐ MOST POPULAR',
      featured: true,
    },
    {
      name: 'Enterprise Plan',
      description: 'For high-traffic & advanced workloads',
      price: 15,
      period: 'month',
      features: [
        { icon: 'check', text: 'Everything in the Pro Plan, plus:', color: 'text-green-400' },
        { icon: 'cpu', text: '5vCPU @ 2.4  GHz (shared)', color: 'text-green-400' },
        { icon: 'memory-stick', text: '10 GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '100 GB NVMe Storage', color: 'text-green-400' },
        { icon: 'infinity', text: 'Unlimited Domain Slots', color: 'text-green-400' },
        { icon: 'heart-handshake', text: '24/7 Dedicated Support', color: 'text-green-400' },
        { icon: 'shield', text: 'Advanced Security', color: 'text-green-400' },
        { icon: 'network', text: 'Optional Add-on: Dedicated IP: $5 AUD / month', color: 'text-blue-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/enterprise-plan',
      badge: null,
      featured: false,
    },
    {
      name: 'Ultra Plan',
      description: 'Ultimate solution for agencies & corporate use',
      price: 30,
      period: 'month',
      features: [
        { icon: 'check', text: 'Everything in the Enterprise Plan, plus:', color: 'text-green-400' },
        { icon: 'cpu', text: '6 vCPU @ 2.4  GHz (shared)', color: 'text-green-400' },
        { icon: 'memory-stick', text: '15 GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '200 GB NVMe Storage', color: 'text-green-400' },
        { icon: 'mail-plus', text: 'Unlimited Email Accounts', color: 'text-green-400' },
        { icon: 'infinity', text: 'Unlimited Domain Slots', color: 'text-green-400' },
        { icon: 'shield', text: 'Advanced Security Suite', color: 'text-green-400' },
        { icon: 'network', text: 'Free Optional Add-on: Dedicated IP', color: 'text-green-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/ultra-plan',
      badge: null,
      featured: false,
    },
    {
      name: 'Power Plan',
      description: 'For maximum performance, shared resources',
      price: 50,
      period: 'month',
      features: [
        { icon: 'cpu', text: '8 vCPU @ 2.4  GHz (shared)', color: 'text-green-400' },
        { icon: 'memory-stick', text: 'Unmetered RAM usage (shared)', color: 'text-green-400' },
        { icon: 'hard-drive', text: '500 GB NVMe Storage', color: 'text-green-400' },
        { icon: 'mail-plus', text: 'Unlimited Email Accounts', color: 'text-green-400' },
        { icon: 'infinity', text: 'Unlimited Domain Slots', color: 'text-green-400' },
        { icon: 'heart-handshake', text: '24/7 Dedicated Support', color: 'text-green-400' },
        { icon: 'shield', text: 'Advanced Security', color: 'text-green-400' },
        { icon: 'network', text: 'Free Optional Add-on: Dedicated IP', color: 'text-green-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/power-plan',
      badge: null,
      featured: false,
    },
  ],
  yearly: [
    {
      name: 'Basic Plan',
      description: 'Perfect for individuals',
      price: 70,
      period: 'year',
      features: [
        { icon: 'check', text: 'Everything in Free Plan, plus some upgrades:', color: 'text-green-400' },
        { icon: 'cpu', text: '3 vCPU @ 2.4 GHz', color: 'text-green-400' },
        { icon: 'memory-stick', text: '7GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '15GB NVMe Storage', color: 'text-green-400' },
        { icon: 'mail-plus', text: 'Unlimited Email Accounts', color: 'text-green-400' },
        { icon: 'check', text: '3 Domain Slots', color: 'text-green-400' },
        { icon: 'help-circle', text: 'Basic Support', color: 'text-green-400' },
        { icon: 'infinity', text: 'Unlimited Bandwidth', color: 'text-green-400' },
        { icon: 'database', text: 'Unlimited Databases', color: 'text-green-400' },
        { icon: 'globe', text: 'WordPress Access', color: 'text-blue-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/basic-plan',
      badge: null,
      featured: false,
    },
    {
      name: 'Pro Plan',
      description: 'Ideal for growing businesses',
      price: 110,
      period: 'year',
      features: [
        { icon: 'check', text: 'Everything in Basic Plan, plus some upgrades:', color: 'text-green-400' },
        { icon: 'cpu', text: '4 vCPU @ 2.4 GHz', color: 'text-green-400' },
        { icon: 'memory-stick', text: '10GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '25GB NVMe Storage', color: 'text-green-400' },
        { icon: 'mail-plus', text: 'Unlimited Email Accounts', color: 'text-green-400' },
        { icon: 'check', text: '8 Domain Slots', color: 'text-green-400' },
        { icon: 'hand-helping', text: 'Priority Support', color: 'text-green-400' },
        { icon: 'laptop-minimal-check', text: 'Early Developer Features', color: 'text-green-400' },
        { icon: 'check', text: 'Access to our VPN services', color: 'text-green-400' },
        { icon: 'hourglass', text: 'DDoS Protection (Coming Soon)', color: 'text-yellow-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/pro-plan',
      badge: null,
      featured: false,
    },
    {
      name: 'Enterprise Plan',
      description: 'For large-scale operations',
      price: 210,
      period: 'year',
      features: [
        { icon: 'check', text: 'Everything in Pro Plan, plus some upgrades:', color: 'text-green-400' },
        { icon: 'cpu', text: '5 vCPU @ 2.4 GHz', color: 'text-green-400' },
        { icon: 'memory-stick', text: '13GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '100GB NVMe Storage', color: 'text-green-400' },
        { icon: 'mail-plus', text: 'Unlimited Email Accounts', color: 'text-green-400' },
        { icon: 'infinity', text: 'Unlimited Domain Slots', color: 'text-green-400' },
        { icon: 'heart-handshake', text: '24/7 Dedicated Support', color: 'text-green-400' },
        { icon: 'shield', text: 'Advanced Security', color: 'text-green-400' },
        //{ icon: 'users', text: '10 Reseller Slots', color: 'text-blue-400', opacity: true, badges: [{ text: 'Requires Contract', class: 'bg-yellow-700' }, { text: 'Coming Soon', class: 'bg-gray-700' }] },
       // { icon: 'user-check', text: '10 Customer Slots', color: 'text-blue-400' },
        { icon: 'plus-square', text: 'Upgrade: $10 for 5 more slots', color: 'text-blue-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/enterprise-plan',
      badge: 'Most Popular',
      featured: true,
    },
    {
      name: 'Ultra Plan',
      description: 'Ultimate solution for all your needs, ideal for corporate businesses',
      price: 360,
      period: 'year',
      features: [
        { icon: 'check', text: 'Everything in Enterprise Plan, plus some upgrades:', color: 'text-green-400' },
        { icon: 'mail-plus', text: 'Unlimited Email Accounts', color: 'text-green-400' },
        { icon: 'hard-drive', text: 'Custom NVMe Storage', color: 'text-green-400' },
        { icon: 'shield', text: 'Advanced Security', color: 'text-green-400' },
        { icon: 'users', text: '15 Reseller Slots', color: 'text-blue-400', opacity: true, badges: [{ text: 'Requires Contract', class: 'bg-yellow-700' }, { text: 'Coming Soon', class: 'bg-gray-700' }] },
        { icon: 'user-check', text: '15 Customer Slots', color: 'text-blue-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/ultra-plan',
      badge: null,
      featured: false,
    },
  ],
  vpn: [
    {
      name: 'Free VPN',
      description: 'Get started with basic VPN protection',
      price: 0,
      period: 'month',
      features: [
        { icon: 'check', text: '1 Server Location', color: 'text-green-400' },
        { icon: 'check', text: 'Basic Encryption', color: 'text-green-400' },
        { icon: 'check', text: 'No device limits', color: 'text-green-400' },
        { icon: 'help-circle', text: 'Basic Support', color: 'text-blue-400' },
      ],
      buttonText: 'Get Free VPN',
      buttonUrl: 'https://platform.neonnextgeneration.com/vpn/free',
      badge: null,
      featured: false,
    },
    {
      name: 'VPN Plan',
      description: 'Secure your online presence',
      price: 3.99,
      period: 'month',
      features: [
        { icon: 'hourglass', text: 'Own IP (Coming Soon)', color: 'text-yellow-400' },
        { icon: 'check', text: 'Can torrent freely', color: 'text-green-400' },
        { icon: 'check', text: 'Multiple locations that allow torrenting', color: 'text-green-400' },
        { icon: 'check', text: 'No bandwidth limits', color: 'text-green-400' },
        { icon: 'check', text: 'No device limits', color: 'text-green-400' },
      ],
      buttonText: 'Get VPN',
      buttonUrl: 'https://buy.stripe.com/28EeVdeXd1qW8f2gwP5wI00',
      badge: null,
      featured: false,
    },
  ],
  vpc: [
    {
      name: 'Basic Plan',
      description: 'Great for testing and small projects',
      price: 1.50,
      period: 'month',
      features: [
        { icon: 'cpu', text: '1 vCPU @ 2.4 GHz', color: 'text-green-400' },
        { icon: 'memory-stick', text: '2.5GB DDR4 RAM', color: 'text-green-400' },
        { icon: 'hard-drive', text: '3GB NVMe Storage', color: 'text-green-400' },
        { icon: 'gauge', text: '50GB Bandwidth', color: 'text-yellow-400' },
        { icon: 'network', text: 'Shared IP', color: 'text-blue-400' },
        { icon: 'database', text: '1 Database Slot', color: 'text-purple-400' },
        { icon: 'hard-drive', text: 'Upgrade storage: $3 for 10GB', color: 'text-blue-400' },
      ],
      buttonText: 'Choose Plan',
      buttonUrl: 'https://billing.neonnextgeneration.com/products/hosting-plans/basic-plan',
      badge: null,
      featured: false,
    },
  ],
};
